### ISSUE TITLE
404 Calendar Widget

### ISSUE THREAD

**Issue by angelorocha** [thingsym/custom-post-type-widgets#1]
When i click on any day, using the calendar widget get the error 404.

**Comment by thingsym** [comment]
Maybe, you may need to edit the permalink of custom post type.

By default, WordPress will not work Date-based permalinks of custom post type.

Recommend that you install the plugin in order to edit the permalink, if you are using a Date-based permalinks by the calendar widget.

And try the following:

Custom Post Type Rewrite
https://wordpress.org/plugins/custom-post-type-rewrite/

or

Custom Post Type Permalinks
https://wordpress.org/plugins/custom-post-type-permalinks/
